# Generated by Django 4.2.5 on 2023-09-11 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 11, 14, 43, 22, 293402, tzinfo=datetime.timezone.utc)),
        ),
    ]
