# Generated by Django 4.2.5 on 2023-09-11 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_resettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 11, 16, 15, 57, 557364, tzinfo=datetime.timezone.utc)),
        ),
    ]
