# Generated by Django 4.2.5 on 2023-09-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.CharField(default=1, max_length=6),
        ),
    ]
