# Generated by Django 4.2.5 on 2023-09-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Added_Image',
        ),
    ]
